davis/stock_api_server/config/routes.rb
Rails.application.routes.draw do
  resources :turnovers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

davis/stock_api_server/app/models/Crawl.rb
class Crawl
    require 'wombat'


    def self.crawl
      Wombat.crawl do
        base_url "https://www.github.com"
        path "/"

        headline xpath: "//h1"
        subheading css: "p.subheading"

        what_is({ css: ".one-half h3" }, :list)

        links do
          explore xpath: '//*[@class="wrapper"]/div[1]/div[1]/div[2]/ul/li[1]/a' do |e|
            e
            # e.gsub(/Explore/, "Love")
          end

          features css: '.features'
          enterprise css: '.enterprise'
          blog css: '.blog'
        end
      end
    end
end

davis/stock_api_server/app/models/turnover.rb
class Turnover
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  store_in collection: "Turnover", database: "turnovers"

  field :day
  field :range
  field :number
  field :name
  field :startPrice
  field :highestPrice
  field :lowestPrice
  field :yesClose
  field :todayClose
  field :dealPrice
  field :dealDelta

  def mongoize
    {
      :range => self.range,
      :number => self.number,
      :name => self.name,
      :startPrice => self.startPrice,
      :highestPrice => self.highestPrice,
      :lowestPrice => self.lowestPrice,
      :yesClose => self.yesClose,
      :todayClose => self.todayClose,
      :dealPrice => self.dealPrice,
      :dealDelta => self.dealDelta
    }
  end

  class << self
    def demongoize(object)
      Turnover.new(
        range: object["range"],
        number: object["number"],
        name: object["name"],
        startPrice: object["startPrice"],
        highestPrice: object["highestPrice"],
        lowestPrice: object["lowestPrice"],
        yesClose: object["yesClose"],
        todayClose: object["todayClose"],
        dealPrice: object["dealPrice"],
        dealDelta: object["dealDelta"]
      )
    end

    def mongoize(object)
      case object
      when Turnover then object.mongoize
      else object
      end
    end
  end
end

davis/stock_api_server/app/models/turnover_per_day.rb
class TurnoverPerDay
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  store_in collection: "TurnoverPerDay", database: "turnovers"
  field :day
  field :turnovers

  def addTrunover(trunover)
    self.turnovers.push(trunover.mongoize)
  end
end

davis/stock_api_server/app/controllers/turnovers_controller.rb
class TurnoversController < ApplicationController
  before_action :set_turnover, only: [:show, :edit, :update, :destroy]

  # GET /turnovers
  # GET /turnovers.json
  # def index
  #   # @turnovers = Turnover.all
  # end
  def index
    oneDayTurnovers = TurnoverPerDay.new
    oneDayTurnovers.day = DateTime.now.beginning_of_day
    oneDayTurnovers.turnovers = []

    [[1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10]].each{ |obj|
        oneTurnover = Turnover.new(range: obj[0], number: obj[1], name: obj[2], startPrice: obj[3], highestPrice: obj[4], lowestPrice: obj[5], yesClose: obj[6], todayClose: obj[7], dealPrice: obj[8], dealDelta: obj[9])
        oneTurnover.day = DateTime.now.beginning_of_day
        oneTurnover.save!
        oneDayTurnovers.addTrunover(oneTurnover)
    }
    oneDayTurnovers.save!

    render json: Crawl.crawl
    # render json: { :hello=> "hello" }
  end

  # GET /turnovers/1
  # GET /turnovers/1.json
  def show
  end

  # GET /turnovers/new
  def new
    @turnover = Turnover.new
  end

  # GET /turnovers/1/edit
  def edit
  end

  # POST /turnovers
  # POST /turnovers.json
  def create
    @turnover = Turnover.new(turnover_params)

    respond_to do |format|
      if @turnover.save
        format.html { redirect_to @turnover, notice: 'Turnover was successfully created.' }
        format.json { render :show, status: :created, location: @turnover }
      else
        format.html { render :new }
        format.json { render json: @turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turnovers/1
  # PATCH/PUT /turnovers/1.json
  def update
    respond_to do |format|
      if @turnover.update(turnover_params)
        format.html { redirect_to @turnover, notice: 'Turnover was successfully updated.' }
        format.json { render :show, status: :ok, location: @turnover }
      else
        format.html { render :edit }
        format.json { render json: @turnover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turnovers/1
  # DELETE /turnovers/1.json
  def destroy
    @turnover.destroy
    respond_to do |format|
      format.html { redirect_to turnovers_url, notice: 'Turnover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turnover
      @turnover = Turnover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turnover_params
      params.fetch(:turnover, {})
    end
end

davis/stock_api_server/app/helpers/turnovers_helper.rb
module TurnoversHelper
end

davis/stock_api_server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApiServer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

davis/stock_api_server/app/views/turnovers/_form.html.erb
<%= form_for(turnover) do |f| %>
  <% if turnover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turnover.errors.count, "error") %> prohibited this turnover from being saved:</h2>

      <ul>
      <% turnover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

davis/stock_api_server/app/views/turnovers/edit.html.erb
<h1>Editing Turnover</h1>

<%= render 'form', turnover: @turnover %>

<%= link_to 'Show', @turnover %> |
<%= link_to 'Back', turnovers_path %>

davis/stock_api_server/app/views/turnovers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turnovers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turnovers.each do |turnover| %>
      <tr>
        <td><%= link_to 'Show', turnover %></td>
        <td><%= link_to 'Edit', edit_turnover_path(turnover) %></td>
        <td><%= link_to 'Destroy', turnover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turnover', new_turnover_path %>

davis/stock_api_server/app/views/turnovers/new.html.erb
<h1>New Turnover</h1>

<%= render 'form', turnover: @turnover %>

<%= link_to 'Back', turnovers_path %>

davis/stock_api_server/app/views/turnovers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_turnover_path(@turnover) %> |
<%= link_to 'Back', turnovers_path %>